apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  {{- if $.Values.storagecluster_annotations }}
  annotations:
    {{- tpl (toYaml $.Values.storagecluster_annotations) $ | nindent 4 }}
  {{- end }}
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
  {{- if $.Values.storagecluster_labels }}
    {{- tpl (toYaml $.Values.storagecluster_labels) $ | nindent 4 }}
  {{- end }}
  name: {{ $.Values.storagecluster_name }}
  namespace: {{ $.Values.storagecluster_namespace }}
spec:
  arbiter: {}
  encryption:
    kms: {}
  externalStorage: {}
  managedResources:
    cephBlockPools: {}
    cephConfig: {}
    cephDashboard: {}
    cephFilesystems: {}
    cephObjectStoreUsers: {}
    cephObjectStores: {}
  mirroring: {}
  nodeTopologies: {}
  storageDeviceSets:
  - config: {}
    count: 1
    dataPVCTemplate:
      metadata: {}
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{ $.Values.storagecluster_storage }}
        storageClassName: {{ $.Values.storagecluster_storageclass }}
        volumeMode: Block
      status: {}
    name: ocs-deviceset-{{ $.Values.storagecluster_storageclass }}
    placement: {}
    portable: true
    preparePlacement: {}
    replica: 3
    resources: {}
  version: 4.11.0
