apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: cluster-admin-rbac
policyDefaults:
  complianceType: musthave
  namespace: management-stack-gitops
  placement:
    clusterSelector:
      matchExpressions:
      - key: vendor
        operator: In
        values:
          - OpenShift
      - key: local-cluster
        operator: DoesNotExist
policies:
  - manifests:
      - path: cluster-admin-group-binding.yaml
      - path: cluster-admin-group.yaml
    name: cluster-admin-rbac
    remediationAction: enforce
