kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "common.names.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ template "common.names.fullname" . }}-argocd-application-controller
    namespace: {{ template "common.names.namespace" $ }}
  - kind: ServiceAccount
    name: {{ template "common.names.fullname" . }}-argocd-applicationset-controller
    namespace: {{ template "common.names.namespace" $ }}
  - kind: ServiceAccount
    name: {{ template "common.names.fullname" . }}-argocd-server
    namespace: {{ template "common.names.namespace" $ }}
