apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshift-mini-console-sa-role
  namespace: omc-app
rules:
  - apiGroups:
      - "*"
    resources:
      - clusterversions
      - infrastructures
      - infrastructures
      - machinesets
      - nodes
      - routes
    verbs:
      - get
      - list
      - watch
