apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openshift-mini-console
    app.kubernetes.io/component: openshift-mini-console
    app.kubernetes.io/instance: openshift-mini-console
  name: openshift-mini-console
  namespace: omc-app
spec:
  replicas: 2
  selector:
    matchLabels:
      deployment: openshift-mini-console
  strategy: {}
  template:
    metadata:
      labels:
        deployment: openshift-mini-console
    spec:
      serviceAccountName: openshift-mini-console-sa
      containers:
      - image: quay.io/nasx/openshift-mini-console:latest
        name: openshift-mini-console
        ports:
        - containerPort: 5000
          name: flask
          protocol: TCP
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
