---
central_annotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  argocd.argoproj.io/sync-wave: "3"
central_name: stackrox-central-services
central_namespace: stackrox
central_persistent_volume_name: stackrox-db
central_persistent_volume_storage_class: thin

# Values for ACS PostSync Job
postsync_job_active_deadline_seconds: 600
postsync_job_annotations:
  argocd.argoproj.io/hook: PostSync
  argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
postsync_job_ansible_config: $GIT_DIRECTORY/ansible/ansible.cfg
postsync_job_ansible_playbook: ansible/playbooks/acs-bootstrap.yaml
postsync_job_git_directory: /tmp/git/management-stack-gitops
postsync_job_git_url: https://github.com/nasx/uc2-gitops.git
postsync_job_image: quay.io/nasx/gitops-ansible-runner:latest
postsync_job_name: acs-postsync-job
postsync_job_namespace: ansible-runner
postsync_job_serviceaccount: ansible-runner-sa
