apiVersion: v1
data:
  bindPassword: '{{hub fromSecret "openshift-config" "oauth-ldap-bind-secret" "bindPassword" hub}}'
kind: Secret
metadata:
  name: oauth-ldap-bind-secret
  namespace: openshift-config
type: Opaque
