apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - ldap:
      attributes:
        email:
        - mail
        id:
        - dn
        name:
        - cn
        preferredUsername:
        - uid
      bindDN: uid=ocp-service-account,cn=users,cn=accounts,dc=lab,dc=uc2,dc=io
      bindPassword:
        name: oauth-ldap-bind-secret
      ca:
        name: oauth-ldap-ca-config-map
      insecure: false
      url: ldap://idm1.lab.uc2.io/cn=users,cn=accounts,dc=lab,dc=uc2,dc=io?uid
    mappingMethod: claim
    name: UC2 IdM
    type: LDAP
