apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: oauth-configuration
policyDefaults:
  complianceType: musthave
  namespace: openshift-config
  placement:
    clusterSelector:
      matchExpressions:
      - key: vendor
        operator: In
        values:
          - OpenShift
      - key: local-cluster
        operator: DoesNotExist
policies:
  - manifests:
      - path: ldap-bind-password.yaml
      - path: ldap-ca.yaml
      - path: oauth.yaml
    name: oauth-configuration
    remediationAction: enforce
