apiVersion: v1
kind: ResourceQuota
metadata:
  name: myapp-dev-quota
  namespace: myapp-dev
spec:
  hard:
    persistentvolumeclaims: "10"
    requests.storage: 100Gi
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
