apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
  name: {{ template "common.names.fullname" . }}
  namespace: {{ template "common.names.namespace" $ }}
spec:
  channel: {{ required "Operator channel is required!" .Values.operator.channel }}
{{- if .Values.config }}
  config:
  {{- tpl (toYaml .Values.config) $ | nindent 4 }}
{{- end }}
  installPlanApproval: {{ .Values.operator.installPlanApproval }}
  name: {{ required "Operator name is required!" .Values.operator.name }}
  source: {{ required "Operator source is required!" .Values.operator.source }}
  sourceNamespace: {{ required "Operator source namespace is required!" .Values.operator.sourceNamespace }}
