apiVersion: batch/v1
kind: Job
metadata:
  {{- if $.Values.presync_job_annotations }}
  annotations:
    {{- tpl (toYaml $.Values.presync_job_annotations) $ | nindent 4 }}
  {{- end }}
  labels:
    run: {{ $.Values.presync_job_name }}
    {{- include "common.labels.labels" $ | nindent 4 }}
  {{- if $.Values.presync_job_labels }}
    {{- tpl (toYaml $.Values.presync_job_labels) $ | nindent 4 }}
  {{- end }}
  name: {{ $.Values.presync_job_name }}
  namespace: {{ $.Values.presync_job_namespace }}
spec:
  template:
    spec:
      activeDeadlineSeconds: {{ $.Values.presync_job_active_deadline_seconds }}
      containers:
        - image: {{ $.Values.presync_job_image }}
          env:
            - name: GIT_DIRECTORY
              value: "{{ $.Values.presync_job_git_directory }}"
            - name: GIT_URL
              value: "{{ $.Values.presync_job_git_url }}"
            - name: ANSIBLE_PLAYBOOK
              value: "{{ $.Values.presync_job_ansible_playbook }}"
            - name: ANSIBLE_CONFIG
              value: "{{ $.Values.presync_job_ansible_config }}"
          command:
            - /bin/bash
            - -c
            - |
              mkdir -p $GIT_DIRECTORY
              git clone $GIT_URL $GIT_DIRECTORY
              ansible-galaxy collection install -r $GIT_DIRECTORY/ansible/collections/requirements.yaml
              ansible-playbook $GIT_DIRECTORY/$ANSIBLE_PLAYBOOK \
                -e multiclusterhub_namespace={{ $.Values.multiclusterhub_namespace }} \
                -e multiclusterobservability_alert_manager_storage_size={{ $.Values.multiclusterobservability_alert_manager_storage_size }} \
                -e multiclusterobservability_compact_storage_size={{ $.Values.multiclusterobservability_compact_storage_size }} \
                -e multiclusterobservability_name={{ $.Values.multiclusterobservability_name }} \
                -e multiclusterobservability_namespace={{ $.Values.multiclusterobservability_namespace }} \
                -e multiclusterobservability_obc_name={{ $.Values.multiclusterobservability_obc_name }} \
                -e multiclusterobservability_obc_namespace={{ $.Values.multiclusterobservability_obc_namespace }} \
                -e multiclusterobservability_pull_secret_name={{ $.Values.multiclusterobservability_pull_secret_name }} \
                -e multiclusterobservability_receive_storage_size={{ $.Values.multiclusterobservability_receive_storage_size }} \
                -e multiclusterobservability_rules_storage_size={{ $.Values.multiclusterobservability_rules_storage_size }} \
                -e multiclusterobservability_storage_class={{ $.Values.multiclusterobservability_storage_class }} \
                -e multiclusterobservability_store_storage_size={{ $.Values.multiclusterobservability_store_storage_size }} \
                -e multiclusterobservability_thanos_secret_name={{ $.Values.multiclusterobservability_thanos_secret_name }}
          imagePullPolicy: Always
          name: ansible-runner
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: {{ $.Values.presync_job_serviceaccount }}
      serviceAccountName: {{ $.Values.presync_job_serviceaccount }}
      terminationGracePeriodSeconds: 30
