---
mcp:
  - name: infra
    matchExpressions:
      - key: machineconfiguration.openshift.io/role
        operator: In
        values:
        - worker
        - infra
    matchLabels:
      - key: node-role.kubernetes.io/infra
        value: ""
    maxUnavailable: 1
    paused: false
  - name: odf
    matchExpressions:
      - key: machineconfiguration.openshift.io/role
        operator: In
        values:
        - worker
        - odf
    matchLabels:
      - key: node-role.kubernetes.io/odf
        value: ""
    maxUnavailable: 1
    paused: false
