---
storagecluster_annotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  argocd.argoproj.io/sync-wave: "2"
  cluster.ocs.openshift.io/local-devices: "true"
  uninstall.ocs.openshift.io/cleanup-policy: delete
  uninstall.ocs.openshift.io/mode: graceful
storagecluster_enablecephtools: "true"
storagecluster_mon_storage: 50Gi
storagecluster_mon_storageclass: thin-csi
storagecluster_mgr_enableactivepassive: "true"
storagecluster_name: odf-storagecluster
storagecluster_namespace: openshift-storage
storagecluster_storage: 2Ti
storagecluster_storageclass: thin-csi
storagecluster_use_localstorage: "false"
