---
storagecluster_annotations:
  uninstall.ocs.openshift.io/cleanup-policy: delete
  uninstall.ocs.openshift.io/mode: graceful
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  argocd.argoproj.io/sync-wave: "2"
storagecluster_name: odf-storagecluster
storagecluster_namespace: openshift-storage
storagecluster_storage: 2Ti
storagecluster_storageclass: thin-csi
