{{ range .Values.mcp }}
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  {{- if .annotations }}
  annotations:
    {{- tpl (toYaml .annotations) $ | nindent 4 }}
  {{- end }}
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
  {{- if .labels }}
    {{- tpl (toYaml .labels) $ | nindent 4 }}
  {{- end }}
  name: {{ .name }}
spec:
  machineConfigSelector:
    matchExpressions:
    {{- range .matchExpressions }}
    - key: {{ .key }}
      operator: {{ .operator }}
      values:
      {{- range .values }}
      - {{ . }}
      {{- end }}
    {{- end }}
  maxUnavailable: {{ .maxUnavailable | int }}
  nodeSelector:
    matchLabels:
    {{- range .matchLabels }}
      {{ .key }}: {{ .value | quote }}
    {{- end }}
  paused: {{ .paused }}
{{ end }}
