- name: Setup Cloud Networking
  gather_facts: false
  hosts: localhost
  roles:
    - role: cloud-networking

- name: Bootstrap Tailscale Subnet Routers
  become: true
  gather_facts: false
  hosts: subnet_routers
  roles:
    - role: tailscale
