---
lvs_annotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  argocd.argoproj.io/sync-wave: "2"
lvs_devicetypes:
  - disk
  - part
lvs_maxsize: 2000Gi
lvs_minsize: 400Gi
lvs_name: odf-localvolumeset
lvs_namespace: openshift-local-storage
lvs_nodeselectorterms:
  - matchExpressions:
    - key: kubernetes.io/hostname
      operator: In
      values:
      - odf0.alice.lab.uc2.io
      - odf1.alice.lab.uc2.io
      - odf2.alice.lab.uc2.io
lvs_storageclass: odf-localvolumeset
lvs_volumemode: Block
