---
# General LokiStack Values
lokistack_s3_secret_name: loki-s3
lokistack_s3_secret_namespace: openshift-logging
lokistack_obc_annotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous
  argocd.argoproj.io/hook: PreSync
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
lokistack_obc_generate_bucket_name: logging
lokistack_obc_name: logging-obc
lokistack_obc_namespace: openshift-logging

# LokiStack Configuration
lokistack_name: logging-loki
lokistack_namespace: openshift-logging
lokistack_tenants:
  mode: openshift-logging
lokistack_management_state: Managed
lokistack_storage_secret_name: loki-s3
lokistack_storage_secret_type: s3
lokistack_storage_tls_ca_name: openshift-service-ca.crt
lokistack_storage_tls_ca_key: service-ca.crt
lokistack_size: 1x.small
lokistack_storageclass_name: odf-storagecluster-ceph-rbd

# Values for LokiStack PreSync Job
lokistack_presync_job_active_deadline_seconds: 600
lokistack_presync_job_annotations:
  argocd.argoproj.io/hook: PreSync
lokistack_presync_job_ansible_config: $GIT_DIRECTORY/ansible/ansible.cfg
lokistack_presync_job_ansible_playbook: ansible/playbooks/lokistack-init.yaml
lokistack_presync_job_git_directory: /tmp/git/management-stack-gitops
lokistack_presync_job_git_url: https://github.com/nasx/uc2-gitops.git
lokistack_presync_job_image: quay.io/nasx/gitops-ansible-runner:latest
lokistack_presync_job_name: lokistack-presync-job
lokistack_presync_job_namespace: ansible-runner
lokistack_presync_job_serviceaccount: ansible-runner-sa
