---
# General Logging Values
logging_loki_s3_secret_name: loki-s3
logging_loki_s3_secret_namespace: openshift-logging
logging_obc_annotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous
  argocd.argoproj.io/hook: PreSync
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
logging_obc_generate_bucket_name: logging
logging_obc_name: logging-obc
logging_obc_namespace: openshift-logging

# Values for Logging PreSync Job
presync_job_active_deadline_seconds: 600
presync_job_annotations:
  argocd.argoproj.io/hook: PreSync
  argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
presync_job_ansible_config: $GIT_DIRECTORY/ansible/ansible.cfg
presync_job_ansible_playbook: ansible/playbooks/logging-init.yaml
presync_job_git_directory: /tmp/git/management-stack-gitops
presync_job_git_url: https://github.com/nasx/uc2-gitops.git
presync_job_image: quay.io/nasx/gitops-ansible-runner:latest
presync_job_name: presync-job
presync_job_namespace: ansible-runner
presync_job_serviceaccount: ansible-runner-sa
