---
# General Logging Values
logging_loki_s3_secret_name: loki-s3
logging_loki_s3_secret_namespace: openshift-logging
logging_obc_annotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous
  argocd.argoproj.io/hook: PreSync
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
logging_obc_generate_bucket_name: logging
logging_obc_name: logging-obc
logging_obc_namespace: openshift-logging

# LokiStack Configuration

lokistack_name: logging-loki
lokistack_namespace: openshift-logging
lokistack_tenants:
  mode: openshift-logging
lokistack_management_state: Managed
lokistack_storage_secret_name: loki-s3
lokistack_storage_secret_type: s3
lokistack_storage_tls_ca_name: openshift-service-ca.crt
lokistack_storage_tls_ca_key: service-ca.crt
lokistack_size: 1x.small
lokistack_storageclass_name: odf-storagecluster-ceph-rbd

# Values for Logging PreSync Job
logging_presync_job_active_deadline_seconds: 600
logging_presync_job_annotations:
  argocd.argoproj.io/hook: PreSync
logging_presync_job_ansible_config: $GIT_DIRECTORY/ansible/ansible.cfg
logging_presync_job_ansible_playbook: ansible/playbooks/logging-init.yaml
logging_presync_job_git_directory: /tmp/git/management-stack-gitops
logging_presync_job_git_url: https://github.com/nasx/uc2-gitops.git
logging_presync_job_image: quay.io/nasx/gitops-ansible-runner:latest
logging_presync_job_name: logging-presync-job
logging_presync_job_namespace: ansible-runner
logging_presync_job_serviceaccount: ansible-runner-sa
