---
# OpenShift GitOps
config:
  env:
    - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
      value: "management-stack-gitops"
    - name: DISABLE_DEFAULT_ARGOCD_INSTANCE
      value: "true"
operator:
  channel: latest
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
operatorgroup:
  create: false

# Initial Namespace Setup
namespaces:
  - annotations:
      openshift.io/description: Management Stack GitOps Resources
      openshift.io/display-name: Management Stack GitOps Resources
    name: management-stack-gitops
