apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
spec:
  audit:
    profile: Default
  servingCerts:
    namedCertificates:
    - names:
      - api.prod-so1.oe.aws.uc2.io
      servingCertificate:
        name: api-cert
