apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: microcert-api-ingress
rules:
- apiGroups:
  - '*'
  resources:
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - config.openshift.io
  resources:
  - apiservers
  - infrastructures
  verbs:
  - '*'
- apiGroups:
  - operator.openshift.io
  resources:
  - ingresscontrollers
  verbs:
  - '*'

