apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: microcert-api-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: microcert-api-ingress
subjects:
- kind: ServiceAccount
  name: microcert
  namespace: ansible-runner
