---
aap_admin_secret_name: automation-controller-admin-password
aap_admin_token_description: Token for AnsibleJob spawned by ACM
aap_admin_user: admin
aap_default_organization: UC2
aap_hub_credential_name: ACM Hub (alice)
aap_hub_credential_org: UC2
aap_ldap_bind_secret_name: oauth-ldap-bind-secret
aap_ldap_bind_secret_namespace: openshift-config
aap_manifest_path: /var/secrets/aap-manifest/manifest.zip
aap_namespace: aap
aap_route_name: automation-controller
aap_sa_name: aap-cluster-admin
aap_sa_namespace: aap
automation_platform:
  execution_environments:
    - description: UC2 GitOps w/ dnspython
      image: quay.io/nasx/ansible-ee-dnspython
      name: UC2 GitOps
      organization: "{{ aap_default_organization }}"
      pull: missing
  organizations:
    - description: Umbrella Compute Cloud (UC2)
      name: UC2
  projects:
    - description: UC2 Automation
      name: UC2 Automation
      organization: "{{ aap_default_organization }}"
      scm_branch: main
      scm_type: git
      scm_url: https://github.com/nasx/uc2-gitops.git
    - description: ACM Hook Playbooks
      name: ACM Hook Playbooks
      organization: "{{ aap_default_organization }}"
      scm_branch: main
      scm_type: git
      scm_url: https://github.com/nasx/acm-hook-playbooks.git
hub_aap_credential_name: aap
hub_aap_credential_namespace: aap
